---
title: "Analysis"
author: "Koki Ando"
date: "4/23/2019"
output: html_document
---

# Preparation

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(corrplot)
library(treemap)
library(GGally)
library(rpart)
library(rpart.plot)
rent = read.csv("data/cleaned_rent.csv")
getwd()
```

## Data Cleansing

```{r}
names(rent)[14] = "maintenance"
rent = mutate(rent, year = substr(date, 0,4))
rent$year = as.numeric(rent$year)
rent = filter(rent, price <= 10)
rent = filter(rent, year != 1900)
```


# EDA

```{r}
str(rent)
```

## Price Distribution

```{r}
rent %>% 
  ggplot(aes(price)) +
  geom_histogram(binwidth = .2)
```


## Station

```{r}
rent = rent %>% 
  separate(address, into = c("ward", "town"), sep = "区") %>% 
  separate(ward, into = c("city", "ward"), sep = "市")

```

```{r fig.width = 11, fig.height = 7}
rent %>% 
  ggplot(aes(station, fill = ward)) +
  geom_bar() +
  theme_gray(base_family = "HiraKakuPro-W3") +
  coord_flip()
```

### Treemap

```{r fig.width=12, fig.height=7}
station_dat = rent %>% 
  select(ward, station) %>% 
  group_by(ward) %>%
  count(station)
station_dat$ward = paste0(station_dat$ward, "区")
treemap(station_dat, index=c("ward","station"), vSize="n", 
    type="index",                            # How you color the treemap. type help(treemap) for more info
    palette = "Set1",                        # Select your color palette from the RColorBrewer presets or make your own.
    title="My Treemap",                      # Customize your title
    fontsize.title=12 # Size of the title
)
```

## Distance

```{r}
rent %>% 
  filter(methods == "徒歩") %>% 
  ggplot(aes(dis)) +
  geom_histogram(binwidth = 1)
```

## Time Series

```{r fig.width=10, fig.height=6}
ts_dat = data.frame(table(rent$year)) %>% 
  mutate(cum_sum = cumsum(Freq)) %>% 
  select(-Freq)
names(ts_dat) = c("year", "num")
ts_dat$year = as.Date(ts_dat$year, format ="%Y")
ts_dat %>% 
  ggplot(aes(year, num)) +
  geom_point(colour = "blue", alpha = .3) +
  geom_line(colour = "blue")
```

## Correlatinon Check

```{r fig.width = 12, fig.heigt = 9, warning=FALSE, message=FALSE}
num_dat = select(rent, title, area, floor, price, admin, maintenance, dis, deposit, key, renewal, year)
ggpairs(num_dat)
```


```{r}
corrplot(
  cor(select(num_dat, -title)),
  method="color",  
  sig.level = 0.01, 
  insig = "blank",
  addCoef.col = "black", 
  tl.srt=45, 
  type="upper")
```

```{r fig.width=12, fig.height=7, warning=FALSE}
select(num_dat, -title) %>% 
  gather(key = "type", value = "value", -price) %>% 
  ggplot(aes(price, value)) +
  geom_point() +
  facet_wrap(~type, scale = "free") +
  geom_smooth(method = "lm")
```

## Model Comparison

lm, rpart, random forest

```{r}
getwd()
price_model_lm = lm(price ~ ., data = num_dat)
price_model_rpart = rpart(price ~ .,data = select(num_dat, -title))
```

```{r fig.width=12, fig.height=6}
prp(price_model_rpart, type = 4, varlen = 0)
```

## Predicting


```{r fig.width=12, fig.height=7}
num_dat$prediction = predict(price_model_rpart)
num_dat =  mutate(num_dat, residuals = price-prediction)
num_dat %>% 
  ggplot(aes(price, prediction)) +
  geom_point() +
  geom_abline(colour = "blue") +
  labs(title = "Price vs Recursive Partitioning Model")
```


```{r}
num_dat %>% 
  ggplot(aes(prediction, residuals)) +
  geom_pointrange(aes(ymin = 0, ymax = residuals), size = .1) + 
    geom_hline(yintercept = 0, linetype = 3)
```

```{r}
library(WVPlots)
GainCurvePlot(num_dat, "prediction", "price", "Apartment Rent Model")
```

```{r}
num_dat %>% 
  arrange(residuals) %>% 
  tail(5)
num_dat %>% 
  arrange(residuals) %>% 
  head(5)
```



Add MSE MAE, RMSE


```{r}
summary(price_model_rpart)
```

## Residuals


